CREATE TABLE IF NOT EXISTS category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_ko VARCHAR(100) NOT NULL,
    name_en VARCHAR(100) NOT NULL,
    depth INTEGER NOT NULL,
    parent_id BIGINT NULL,
    CONSTRAINT fk_category_parent
        FOREIGN KEY (parent_id) REFERENCES category (id),
    CONSTRAINT chk_category_depth
        CHECK (depth BETWEEN 1 AND 3),
    CONSTRAINT chk_category_parent_by_depth
        CHECK (
            (depth = 1 AND parent_id IS NULL)
            OR (depth IN (2, 3) AND parent_id IS NOT NULL)
        ),
    CONSTRAINT uk_category_name_ko_depth
        UNIQUE (name_ko, depth),
    CONSTRAINT uk_category_name_en_depth
        UNIQUE (name_en, depth)
);

CREATE INDEX IF NOT EXISTS idx_category_parent_id ON category (parent_id);
CREATE INDEX IF NOT EXISTS idx_category_depth ON category (depth);
