ALTER TABLE member
    ADD COLUMN IF NOT EXISTS postal_code VARCHAR(10),
    ADD COLUMN IF NOT EXISTS road_address VARCHAR(255),
    ADD COLUMN IF NOT EXISTS jibun_address VARCHAR(255),
    ADD COLUMN IF NOT EXISTS detail_address VARCHAR(255),
    ADD COLUMN IF NOT EXISTS latitude DECIMAL(10, 7),
    ADD COLUMN IF NOT EXISTS longitude DECIMAL(10, 7),
    ADD COLUMN IF NOT EXISTS location_source VARCHAR(20);
