ALTER TABLE product
    ADD COLUMN IF NOT EXISTS view_count BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS favorite_count BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS chat_count BIGINT NOT NULL DEFAULT 0;
